# Creating Series

In [1]:
# Program for creating Series using series() method of Pandas Library

In [2]:
#Import Pandas library
import pandas as pd

In [3]:
#Creating Student Name List
Name=["amruta","punam","krishna","deep","ayush"]
Name

['amruta', 'punam', 'krishna', 'deep', 'ayush']

In [4]:
#Creating a Series 
Roll_list=pd.Series(Name,index=[1,2,3,4,5])
print(Roll_list)

1     amruta
2      punam
3    krishna
4       deep
5      ayush
dtype: object

# Creating Data Frame

In [5]:
#Import Pandas library
import pandas as pd

In [7]:
#Creating Data Frame
df=pd.DataFrame([[10,12,14,16],[11,18,15,21],[12,13,14,15]],
columns= ["DAA","SQL","MLAI","SE"])

In [8]:
df

   DAA  SQL  MLAI  SE
0   10   12    14  16
1   11   18    15  21
2   12   13    14  15

In [9]:
df.shape

(3, 4)

In [10]:
df.size

12

In [11]:
df.ndim

2

# Adding Record (Row) to the data frame

In [15]:
df2=pd.DataFrame([[5,6,7,8]],
columns= ["DAA","SQL","MLAI","SE"])

In [17]:
df3 = pd.concat([df, df2], ignore_index=True)

In [18]:
df3

   DAA  SQL  MLAI  SE
0   10   12    14  16
1   11   18    15  21
2   12   13    14  15
3    5    6     7   8

# Adding Attribute (Columns) name DM

In [19]:
df3["DM"]=[12,15,16,14]

In [20]:
df3

   DAA  SQL  MLAI  SE  DM
0   10   12    14  16  12
1   11   18    15  21  15
2   12   13    14  15  16
3    5    6     7   8  14

# Deleting Record from  df3 dataframe

In [21]:
df4=df3.drop(index=[1])

In [22]:
df4

   DAA  SQL  MLAI  SE  DM
0   10   12    14  16  12
2   12   13    14  15  16
3    5    6     7   8  14

# Deleting Attribute (Columns) from df3 dataframe

In [23]:
df5=df3.drop(columns=["DM"])

In [24]:
df5

   DAA  SQL  MLAI  SE
0   10   12    14  16
1   11   18    15  21
2   12   13    14  15
3    5    6     7   8

In [26]:
#Finding mean of DSS 

print("Mean of DAA:", df5["DAA"].mean())

Mean of DAA: 9.5

In [28]:
#Finding median of DSS

print("Median of DAA:", df5["DAA"].median())

Median of DAA: 10.5

In [29]:
#Finding mode of DSS

print("Mode of DAA:", df5["DAA"].mode())

Mode of DAA: 0     5
1    10
2    11
3    12
Name: DAA, dtype: int64

In [31]:
#Finding max number of DSS

print("Max of DAA:", df5["DAA"].max())

Max of DAA: 12

In [32]:
#Finding Min number of DSS

print("Max of DAA:", df5["DAA"].min())

Max of DAA: 5